package routegen

import (
	"bytes"
	"context"
	"fmt"
	"go/format"
	"go/token"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const generatedBanner = "Code generated by routegen"

// Options selects the routes directory and the import paths written into generated files.
type Options struct {
	// Dir is the routes directory.
	Dir string
	// ImportPath is the Go import path of this module. Empty means github.com/yurimoinhos/go-n-act.
	ImportPath string
	// TSImport is the TypeScript specifier of this module. Empty means @aggitech/route.
	TSImport string
}

// Generate reads Dir and returns the files that should exist, keyed by absolute path.
// It does not write to disk.
func Generate(ctx context.Context, opt Options) (map[string][]byte, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	if opt.Dir == "" {
		return nil, fmt.Errorf("routegen: missing routes directory")
	}
	if opt.ImportPath == "" {
		opt.ImportPath = "github.com/yurimoinhos/go-n-act"
	}
	if opt.TSImport == "" {
		opt.TSImport = "@aggitech/route"
	}
	dir, err := filepath.Abs(opt.Dir)
	if err != nil {
		return nil, err
	}
	rels, err := scan(dir)
	if err != nil {
		return nil, err
	}
	if err := rejectDollarDirs(rels); err != nil {
		return nil, err
	}
	routes, err := Plan(rels)
	if err != nil {
		return nil, err
	}
	var loadedPkg *loaded
	if hasGo(rels) {
		modRoot, err := findModule(dir)
		if err != nil {
			return nil, err
		}
		loadedPkg, err = loadRoutes(ctx, modRoot, dir)
		if err != nil {
			return nil, err
		}
	}
	sources := map[string]string{}
	for i := range routes {
		route := &routes[i]
		if route.HasGo {
			abs := filepath.Clean(filepath.Join(dir, filepath.FromSlash(route.GoRel)))
			handlers := []goHandler{}
			if loadedPkg != nil {
				handlers = loadedPkg.byFile[abs]
			}
			if len(handlers) == 0 {
				route.HasGo = false
				route.GoRel = ""
			}
		}
		if !route.HasTSX {
			continue
		}
		abs := filepath.Join(dir, filepath.FromSlash(route.TSXRel))
		body, err := os.ReadFile(abs)
		if err != nil {
			return nil, err
		}
		sources[route.Key] = string(body)
		if err := checkRouteSource(route.TSXRel, sources[route.Key], route.Kind, route.Pattern); err != nil {
			return nil, err
		}
	}
	files := map[string][]byte{}
	if err := emitClients(dir, opt.TSImport, routes, loadedPkg, files); err != nil {
		return nil, err
	}
	if err := emitRegisters(dir, opt.ImportPath, routes, loadedPkg, files); err != nil {
		return nil, err
	}
	if tree, ok, err := emitTree(opt.TSImport, routes); err != nil {
		return nil, err
	} else if ok {
		files[filepath.Join(dir, "routeTree.gen.tsx")] = []byte(tree)
	}
	return files, nil
}

// Write creates each generated file. When check is set, Write compares the
// files to disk and leaves the directory unchanged.
func Write(dir string, files map[string][]byte, check bool) error {
	abs, err := filepath.Abs(dir)
	if err != nil {
		return err
	}
	if check {
		return diffGenerated(abs, files)
	}
	for path, body := range files {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, body, 0o644); err != nil {
			return err
		}
	}
	return removeStale(abs, files)
}

func scan(dir string) ([]string, error) {
	var rels []string
	err := filepath.WalkDir(dir, func(name string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(dir, name)
		if err != nil {
			return err
		}
		rels = append(rels, filepath.ToSlash(rel))
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(rels)
	return rels, nil
}

func hasGo(rels []string) bool {
	for _, rel := range rels {
		if strings.HasSuffix(rel, ".go") && !skipRel(rel) {
			return true
		}
	}
	return false
}

func rejectDollarDirs(rels []string) error {
	var bad []string
	for _, rel := range rels {
		if ignoredGoName(rel) {
			bad = append(bad, rel)
		}
	}
	if len(bad) == 0 {
		return nil
	}
	sort.Strings(bad)
	rel := bad[0]
	reason := "Go file names cannot contain $"
	switch {
	case dirHasDollar(rel):
		reason = "Go import paths reject $"
	case strings.HasPrefix(path.Base(rel), "_"):
		reason = "the go tool ignores file names that start with _"
	}
	return fmt.Errorf("routegen: %s: %s. Rename it to %s", rel, reason, suggestGoPath(rel))
}

func ignoredGoName(rel string) bool {
	if !strings.HasSuffix(rel, ".go") {
		return false
	}
	if strings.Contains(rel, "$") {
		return true
	}
	base := path.Base(rel)
	return strings.HasPrefix(base, "_") && !strings.HasSuffix(base, "_test.go")
}

func dirHasDollar(rel string) bool {
	dir := path.Dir(rel)
	if dir == "." || dir == "" {
		return false
	}
	for _, seg := range strings.Split(dir, "/") {
		if strings.Contains(seg, "$") {
			return true
		}
	}
	return false
}

func suggestGoPath(rel string) string {
	ext := path.Ext(rel)
	return rewriteKey(strings.TrimSuffix(rel, ext), true) + ext
}

// goRelFromKey is the .go path for a route key. '$' is rewritten in every
// segment. A pathless token is rewritten only in the file name: a directory
// may start with '_' and still be a valid import path.
func goRelFromKey(key string) string {
	return rewriteKey(key, false) + ".go"
}

func rewriteKey(key string, anyUnderscore bool) string {
	parts := strings.Split(key, "/")
	last := len(parts) - 1
	for i, part := range parts {
		dots := strings.Split(part, ".")
		for j, token := range dots {
			dots[j] = dollarTokenToGo(token, i == last, anyUnderscore)
		}
		parts[i] = strings.Join(dots, ".")
	}
	return strings.Join(parts, "/")
}

func dollarTokenToGo(token string, fileToken, anyUnderscore bool) string {
	if token == "$" {
		return "splat"
	}
	if strings.HasPrefix(token, "$") && routeIdent(token[1:]) {
		return "param_" + token[1:]
	}
	if !fileToken || !strings.HasPrefix(token, "_") {
		return token
	}
	if !anyUnderscore && !isPathless(token) {
		return token
	}
	trimmed := strings.TrimLeft(token, "_")
	if trimmed == "" {
		trimmed = "path"
	}
	return "pathless_" + trimmed
}

func findModule(dir string) (string, error) {
	start := dir
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("routegen: go.mod not found above %s", start)
		}
		dir = parent
	}
}

type endpoint struct {
	route   Route
	handler goHandler
	absDir  string
	absFile string
}

func collectEndpoints(dir string, routes []Route, loadedPkg *loaded) ([]endpoint, error) {
	var out []endpoint
	seenName := map[string]string{}
	for _, route := range routes {
		if !route.HasGo {
			continue
		}
		absFile := filepath.Clean(filepath.Join(dir, filepath.FromSlash(route.GoRel)))
		absDir := filepath.Dir(absFile)
		handlers := loadedPkg.byFile[absFile]
		id := route.Pattern
		if route.Kind == KindRoot {
			id = "__root"
		}
		for _, handler := range handlers {
			key := absDir + "\x00" + handler.Name
			if prev, ok := seenName[key]; ok {
				return nil, fmt.Errorf("routegen: %s and %s both export %s; handler names in one directory must be unique", filepath.Base(prev), filepath.Base(absFile), handler.Name)
			}
			seenName[key] = absFile
			handler.Service = route.Service
			handler.RouteID = id
			handler.File = absFile
			out = append(out, endpoint{route: route, handler: handler, absDir: absDir, absFile: absFile})
		}
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].handler.Service != out[j].handler.Service {
			return out[i].handler.Service < out[j].handler.Service
		}
		if out[i].handler.Name != out[j].handler.Name {
			return out[i].handler.Name < out[j].handler.Name
		}
		return out[i].absFile < out[j].absFile
	})
	return out, nil
}

func emitClients(dir, tsImport string, routes []Route, loadedPkg *loaded, files map[string][]byte) error {
	if loadedPkg == nil {
		return nil
	}
	ends, err := collectEndpoints(dir, routes, loadedPkg)
	if err != nil {
		return err
	}
	byFile := map[string][]goHandler{}
	order := []string{}
	for _, end := range ends {
		if _, ok := byFile[end.absFile]; !ok {
			order = append(order, end.absFile)
		}
		byFile[end.absFile] = append(byFile[end.absFile], end.handler)
	}
	for _, absFile := range order {
		handlers := byFile[absFile]
		sort.Slice(handlers, func(i, j int) bool { return handlers[i].Name < handlers[j].Name })
		built, err := newTSBuilder().file(handlers)
		if err != nil {
			rel, _ := filepath.Rel(dir, absFile)
			return fmt.Errorf("routegen: %s: %w", filepath.ToSlash(rel), err)
		}
		out := strings.TrimSuffix(absFile, ".go") + ".gen.ts"
		files[out] = []byte(renderTS(tsImport, built))
	}
	return nil
}

type childPkg struct {
	alias string
	name  string
	path  string
}

func emitRegisters(dir, importPath string, routes []Route, loadedPkg *loaded, files map[string][]byte) error {
	if loadedPkg == nil {
		return nil
	}
	ends, err := collectEndpoints(dir, routes, loadedPkg)
	if err != nil {
		return err
	}
	if len(ends) == 0 {
		return nil
	}
	byDir := map[string][]endpoint{}
	var dirs []string
	for _, end := range ends {
		if _, ok := byDir[end.absDir]; !ok {
			dirs = append(dirs, end.absDir)
		}
		byDir[end.absDir] = append(byDir[end.absDir], end)
	}
	sort.Strings(dirs)
	rootName := packageName(filepath.Base(dir))
	if pkg := loadedPkg.byDir[filepath.Clean(dir)]; pkg != nil && pkg.Name != "" {
		rootName = pkg.Name
	}
	used := map[string]bool{rootName: true}
	var children []childPkg
	for _, absDir := range dirs {
		if absDir == filepath.Clean(dir) {
			continue
		}
		pkg := loadedPkg.byDir[absDir]
		if pkg == nil || pkg.PkgPath == "" {
			return fmt.Errorf("routegen: %s is not a Go package", absDir)
		}
		alias := pickAlias(pkg.Name, used)
		children = append(children, childPkg{alias: alias, name: pkg.Name, path: pkg.PkgPath})
	}
	sort.Slice(children, func(i, j int) bool { return children[i].path < children[j].path })
	rootDir := filepath.Clean(dir)
	for _, absDir := range dirs {
		if absDir == rootDir {
			continue
		}
		local := renderRegister(loadedPkg.byDir[absDir].Name, importPath, byDir[absDir], nil, true, false)
		body, err := gofmtSource(absDir, local)
		if err != nil {
			return err
		}
		files[filepath.Join(absDir, "register.gen.go")] = body
	}
	rootBody := renderRegister(rootName, importPath, byDir[rootDir], children, len(byDir[rootDir]) > 0, true)
	body, err := gofmtSource(dir, rootBody)
	if err != nil {
		return err
	}
	files[filepath.Join(dir, "register.gen.go")] = body
	return nil
}

func renderRegister(pkgName, importPath string, procs []endpoint, children []childPkg, includeLocal, includeAll bool) string {
	qual := routeQualifier(importPath)
	var b strings.Builder
	b.WriteString("// Code generated by routegen. DO NOT EDIT.\n\npackage ")
	b.WriteString(pkgName)
	b.WriteString("\n\nimport (\n\t")
	b.WriteString(strconv.Quote(importPath))
	b.WriteString("\n")
	if len(children) > 0 {
		b.WriteString("\n")
		for _, child := range children {
			b.WriteByte('\t')
			if child.alias != child.name {
				b.WriteString(child.alias)
				b.WriteByte(' ')
			}
			b.WriteString(strconv.Quote(child.path))
			b.WriteByte('\n')
		}
	}
	b.WriteString(")\n\n")
	if includeLocal {
		b.WriteString("// Register adds this package's procedures to mux.\n")
		fmt.Fprintf(&b, "func Register(mux *%s.Mux) error {\n", qual)
		for _, proc := range procs {
			fmt.Fprintf(&b, "\tif err := mux.Handle(%s.Procedure{\n", qual)
			fmt.Fprintf(&b, "\t\tService: %s,\n", strconv.Quote(proc.handler.Service))
			fmt.Fprintf(&b, "\t\tMethod:  %s,\n", strconv.Quote(proc.handler.Name))
			fmt.Fprintf(&b, "\t\tRouteID: %s,\n", strconv.Quote(proc.handler.RouteID))
			fmt.Fprintf(&b, "\t\tFn:      %s,\n", proc.handler.Name)
			b.WriteString("\t}); err != nil {\n\t\treturn err\n\t}\n")
		}
		b.WriteString("\treturn nil\n}\n")
	}
	if includeAll {
		if includeLocal {
			b.WriteByte('\n')
		}
		b.WriteString("// RegisterAll adds every procedure in this route tree to mux.\n")
		fmt.Fprintf(&b, "func RegisterAll(mux *%s.Mux) error {\n", qual)
		if includeLocal {
			b.WriteString("\tif err := Register(mux); err != nil {\n\t\treturn err\n\t}\n")
		}
		for _, child := range children {
			fmt.Fprintf(&b, "\tif err := %s.Register(mux); err != nil {\n\t\treturn err\n\t}\n", child.alias)
		}
		b.WriteString("\treturn nil\n}\n")
	}
	return b.String()
}

func routeQualifier(importPath string) string {
	base := path.Base(importPath)
	if !token.IsIdentifier(base) || token.IsKeyword(base) {
		return "route"
	}
	return base
}

func packageName(name string) string {
	name = strings.ToLower(sanitize(name))
	if !token.IsIdentifier(name) || token.IsKeyword(name) {
		return "routes"
	}
	return name
}

func pickAlias(name string, used map[string]bool) string {
	base := name
	if !token.IsIdentifier(base) || token.IsKeyword(base) {
		base = "pkg"
	}
	alias := base
	for i := 2; ; i++ {
		if !used[alias] {
			used[alias] = true
			return alias
		}
		alias = fmt.Sprintf("%s%d", base, i)
	}
}

func gofmtSource(dir, src string) ([]byte, error) {
	out, err := format.Source([]byte(src))
	if err != nil {
		return nil, fmt.Errorf("routegen: format %s: %w\n%s", dir, err, src)
	}
	return out, nil
}

func emitTree(tsImport string, routes []Route) (string, bool, error) {
	byKey := map[string]Route{}
	anyTSX := false
	for _, route := range routes {
		byKey[route.Key] = route
		if route.HasTSX {
			anyTSX = true
		}
	}
	if !anyTSX {
		return "", false, nil
	}
	nodes := map[string]*treeNode{}
	for _, route := range routes {
		if route.Kind == KindRoot || route.HasTSX {
			nodes[route.Key] = &treeNode{route: route}
		}
	}
	var root *treeNode
	for _, n := range nodes {
		if n.route.Kind == KindRoot {
			root = n
			continue
		}
		parentKey := tsxParent(n.route, byKey)
		parent := nodes[parentKey]
		if parent == nil {
			return "", false, fmt.Errorf("routegen: %s has no parent route", n.route.Key)
		}
		parent.kids = append(parent.kids, n)
	}
	if root == nil {
		return "", false, fmt.Errorf("routegen: missing root route")
	}
	var walk func(*treeNode)
	walk = func(n *treeNode) {
		sort.Slice(n.kids, func(i, j int) bool {
			if n.kids[i].route.Pattern != n.kids[j].route.Pattern {
				return n.kids[i].route.Pattern < n.kids[j].route.Pattern
			}
			return n.kids[i].route.Key < n.kids[j].route.Key
		})
		for _, kid := range n.kids {
			walk(kid)
		}
	}
	walk(root)

	used := map[string]bool{"RootRoute": true}
	aliases := map[string]string{root.route.Key: "RootRoute"}
	var keys []string
	for key, n := range nodes {
		if n.route.Kind == KindRoot {
			continue
		}
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		aliases[key] = uniqueAlias(key, used)
	}

	var b strings.Builder
	b.WriteString("// Code generated by routegen. DO NOT EDIT.\n\n")
	if root.route.HasTSX {
		fmt.Fprintf(&b, "import type { AnyRoute } from %s;\n\n", strconv.Quote(tsImport))
	} else {
		fmt.Fprintf(&b, "import { Outlet, createRootRoute, type AnyRoute } from %s;\n\n", strconv.Quote(tsImport))
	}
	var styles []string
	for _, key := range keys {
		route := nodes[key].route
		for _, style := range route.Styles {
			styles = append(styles, style)
		}
	}
	for _, style := range root.route.Styles {
		styles = append(styles, style)
	}
	for _, style := range styles {
		fmt.Fprintf(&b, "import %s;\n", strconv.Quote("./"+style))
	}
	if len(styles) > 0 {
		b.WriteByte('\n')
	}
	if root.route.HasTSX {
		fmt.Fprintf(&b, "import { Route as RootRouteImport } from %s;\n", strconv.Quote(importSpec(root.route.TSXRel)))
	}
	for _, key := range keys {
		route := nodes[key].route
		fmt.Fprintf(&b, "import { Route as %sImport } from %s;\n", aliases[key], strconv.Quote(importSpec(route.TSXRel)))
	}
	b.WriteByte('\n')
	if root.route.HasTSX {
		b.WriteString("const RootRoute = RootRouteImport as AnyRoute;\n")
	} else {
		b.WriteString("const RootRoute = createRootRoute({\n")
		b.WriteString("  component: function RootComponent() {\n")
		b.WriteString("    return <Outlet />;\n")
		b.WriteString("  },\n")
		b.WriteString("});\n")
	}
	for _, key := range keys {
		fmt.Fprintf(&b, "const %s = %sImport as AnyRoute;\n", aliases[key], aliases[key])
	}
	b.WriteString("\nexport const routeTree = ")
	writeNode(&b, root, aliases, "")
	b.WriteString(";\n")
	return b.String(), true, nil
}

type treeNode struct {
	route Route
	kids  []*treeNode
}

func writeNode(b *strings.Builder, n *treeNode, aliases map[string]string, indent string) {
	name := aliases[n.route.Key]
	if len(n.kids) == 0 {
		b.WriteString(name)
		return
	}
	b.WriteString(name)
	b.WriteString(".addChildren([\n")
	childIndent := indent + "  "
	for _, kid := range n.kids {
		b.WriteString(childIndent)
		writeNode(b, kid, aliases, childIndent)
		b.WriteString(",\n")
	}
	b.WriteString(indent)
	b.WriteString("])")
}

func tsxParent(route Route, byKey map[string]Route) string {
	key := route.ParentKey
	for key != "" && key != route.Key {
		parent, ok := byKey[key]
		if !ok {
			return "__root"
		}
		if parent.Kind == KindRoot || parent.HasTSX {
			return parent.Key
		}
		key = parent.ParentKey
	}
	return "__root"
}

func uniqueAlias(key string, used map[string]bool) string {
	base := Alias(key)
	alias := base
	for i := 2; ; i++ {
		if !used[alias] {
			used[alias] = true
			return alias
		}
		alias = fmt.Sprintf("%s%d", base, i)
	}
}

func importSpec(rel string) string {
	rel = strings.TrimSuffix(rel, path.Ext(rel))
	return "./" + rel
}

var (
	fileRouteDQ   = regexp.MustCompile(`(?s)createFileRoute\s*\(\s*"([^"]*)"`)
	fileRouteSQ   = regexp.MustCompile(`(?s)createFileRoute\s*\(\s*'([^']*)'`)
	fileRouteBT   = regexp.MustCompile("(?s)createFileRoute\\s*\\(\\s*`([^`]*)`")
	rootRouteRE   = regexp.MustCompile(`createRootRoute\s*\(`)
	exportRouteRE = regexp.MustCompile(`export\s+(?:const|function|\{)\s*Route\b`)
)

func firstFileRoute(src string) (at int, quote, path string, ok bool) {
	at = -1
	consider := func(re *regexp.Regexp, q string) {
		m := re.FindStringSubmatchIndex(src)
		if m == nil || (at >= 0 && m[0] >= at) {
			return
		}
		at = m[0]
		quote = q
		path = src[m[2]:m[3]]
		ok = true
	}
	consider(fileRouteDQ, `"`)
	consider(fileRouteSQ, "'")
	consider(fileRouteBT, "`")
	return at, quote, path, ok
}

func checkRouteSource(rel, src string, kind Kind, pattern string) error {
	fileAt := -1
	fileQuote := ""
	filePath := ""
	if at, quote, path, ok := firstFileRoute(src); ok {
		fileAt = at
		fileQuote = quote
		filePath = path
	}
	rootAt := -1
	if m := rootRouteRE.FindStringIndex(src); m != nil {
		rootAt = m[0]
	}
	if fileAt < 0 && rootAt < 0 {
		if kind == KindRoot {
			return fmt.Errorf("routegen: %s must call createRootRoute(", rel)
		}
		return fmt.Errorf("routegen: %s must call createFileRoute(%q)", rel, pattern)
	}
	if rootAt >= 0 && (fileAt < 0 || rootAt < fileAt) {
		if kind != KindRoot {
			return fmt.Errorf("routegen: %s must call createFileRoute(%q)", rel, pattern)
		}
		if !exportRouteRE.MatchString(src) {
			return fmt.Errorf("routegen: %s must export Route", rel)
		}
		return nil
	}
	if kind == KindRoot {
		return fmt.Errorf("routegen: %s must call createRootRoute(", rel)
	}
	if fileQuote == "`" && strings.Contains(filePath, "${") {
		return fmt.Errorf("routegen: %s createFileRoute path must be a static string", rel)
	}
	if filePath != pattern {
		return fmt.Errorf("routegen: %s calls createFileRoute(%q), want %q", rel, filePath, pattern)
	}
	if !exportRouteRE.MatchString(src) {
		return fmt.Errorf("routegen: %s must export Route", rel)
	}
	return nil
}

func diffGenerated(dir string, files map[string][]byte) error {
	var mismatches []string
	for path, want := range files {
		got, err := os.ReadFile(path)
		if err != nil || !bytes.Equal(got, want) {
			rel, relErr := filepath.Rel(dir, path)
			if relErr != nil {
				rel = path
			}
			mismatches = append(mismatches, filepath.ToSlash(rel))
		}
	}
	stale, err := staleFiles(dir, files)
	if err != nil {
		return err
	}
	mismatches = append(mismatches, stale...)
	if len(mismatches) == 0 {
		return nil
	}
	sort.Strings(mismatches)
	return fmt.Errorf("routegen: generated files are out of date: %s", strings.Join(mismatches, ", "))
}

func removeStale(dir string, files map[string][]byte) error {
	stale, err := staleFiles(dir, files)
	if err != nil {
		return err
	}
	for _, rel := range stale {
		if err := os.Remove(filepath.Join(dir, filepath.FromSlash(rel))); err != nil && !os.IsNotExist(err) {
			return err
		}
	}
	return nil
}

func staleFiles(dir string, files map[string][]byte) ([]string, error) {
	want := map[string]bool{}
	for path := range files {
		want[filepath.Clean(path)] = true
	}
	var stale []string
	err := filepath.WalkDir(dir, func(name string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if want[filepath.Clean(name)] {
			return nil
		}
		body, err := os.ReadFile(name)
		if err != nil {
			return err
		}
		if !managed(name, body) {
			return nil
		}
		rel, err := filepath.Rel(dir, name)
		if err != nil {
			return err
		}
		stale = append(stale, filepath.ToSlash(rel))
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(stale)
	return stale, nil
}

func managed(name string, body []byte) bool {
	base := filepath.Base(name)
	switch {
	case base == "register.gen.go", base == "routeTree.gen.tsx", strings.HasSuffix(base, ".gen.ts"):
	default:
		return false
	}
	head := body
	if len(head) > 240 {
		head = head[:240]
	}
	return bytes.Contains(head, []byte(generatedBanner))
}
