package routegen

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestGenerateRoundTrip(t *testing.T) {
	mod := t.TempDir()
	routes := filepath.Join(mod, "routes")
	writeFixture(t, mod, routes, repoRoot(t))

	files, err := Generate(context.Background(), Options{Dir: routes})
	if err != nil {
		t.Fatal(err)
	}
	indexGen := string(mustGen(t, files, "routes/clients/index.gen.ts"))
	if !strings.Contains(indexGen, "export type ListInInput") || strings.Contains(indexGen, "actor") {
		t.Fatalf("input type leaked or missing:\n%s", indexGen)
	}
	if !strings.Contains(indexGen, `"admin" | "user"`) || !strings.Contains(indexGen, "updated: string") {
		t.Fatalf("types:\n%s", indexGen)
	}
	if !strings.Contains(indexGen, `method: "POST"`) || !strings.Contains(indexGen, `path: "/clients"`) {
		t.Fatalf("client:\n%s", indexGen)
	}
	if !strings.Contains(indexGen, `from "../gnact/client.ts"`) {
		t.Fatalf("embedded client import:\n%s", indexGen)
	}
	if !strings.Contains(indexGen, "Loader lists clients.") {
		t.Fatalf("doc:\n%s", indexGen)
	}
	runtime := string(mustGen(t, files, "routes/gnact/client.ts"))
	if !strings.Contains(runtime, "Code generated by routegen") || !strings.Contains(runtime, "export async function call") {
		t.Fatalf("runtime:\n%s", runtime)
	}
	idGen := string(mustGen(t, files, "routes/clients/param_id.gen.ts"))
	if !strings.Contains(idGen, "id: string") || !strings.Contains(idGen, `method: "GET"`) || !strings.Contains(idGen, `path: "/clients/{id}"`) {
		t.Fatalf("get client:\n%s", idGen)
	}
	register := string(mustGen(t, files, "routes/clients/register.gen.go"))
	if !strings.Contains(register, "Loader") || !strings.Contains(register, "Get") || strings.Contains(register, "Format") {
		t.Fatalf("register:\n%s", register)
	}
	if !strings.Contains(register, `POST(r, "/clients", Loader)`) || !strings.Contains(register, `GET(r, "/clients/{id}", Get)`) {
		t.Fatalf("register verbs:\n%s", register)
	}
	root := string(mustGen(t, files, "routes/register.gen.go"))
	if !strings.Contains(root, "func RegisterAll(") || !strings.Contains(root, "example.com/app/routes/clients") {
		t.Fatalf("root register:\n%s", root)
	}
	tree := string(mustGen(t, files, "routes/routeTree.gen.tsx"))
	for _, want := range []string{"./clients/index.scss", "ClientsIndexRoute", "ClientsParamIdRoute", "ClientsRouteRoute", "<Outlet />", `"./clients/$id"`} {
		if !strings.Contains(tree, want) {
			t.Fatalf("tree missing %s:\n%s", want, tree)
		}
	}
	for path := range files {
		if strings.Contains(filepath.ToSlash(path), "helpers") {
			t.Fatalf("generated a helper route %s", path)
		}
	}

	if err := Write(routes, files, false); err != nil {
		t.Fatal(err)
	}
	if err := Write(routes, files, true); err != nil {
		t.Fatal(err)
	}
	// A second run sees the embedded runtime under routes/gnact/ and must not
	// treat it as routes: generation stays idempotent and -check passes.
	again, err := Generate(context.Background(), Options{Dir: routes})
	if err != nil {
		t.Fatalf("regenerate: %v", err)
	}
	if err := Write(routes, again, true); err != nil {
		t.Fatalf("check after regenerate: %v", err)
	}
	stale := filepath.Join(routes, "clients", "index.gen.ts")
	if err := os.WriteFile(stale, []byte("// Code generated by routegen. DO NOT EDIT.\nexport const stale = true;\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := Write(routes, files, true); err == nil || !strings.Contains(err.Error(), "index.gen.ts") {
		t.Fatalf("check err = %v", err)
	}
	if err := Write(routes, files, false); err != nil {
		t.Fatal(err)
	}

	tidy := exec.Command("go", "mod", "tidy")
	tidy.Dir = mod
	if out, err := tidy.CombinedOutput(); err != nil {
		t.Fatalf("tidy: %v\n%s", err, out)
	}
	test := exec.Command("go", "test", "./routes/clients/")
	test.Dir = mod
	if out, err := test.CombinedOutput(); err != nil {
		t.Fatalf("go test: %v\n%s", err, out)
	}
}

func TestGenerateRejectsDollarDirectory(t *testing.T) {
	dir := t.TempDir()
	routes := filepath.Join(dir, "routes")
	writeFile(t, filepath.Join(routes, "clients", "$id", "route.go"), "package id\n")
	_, err := Generate(context.Background(), Options{Dir: routes})
	if err == nil || !strings.Contains(err.Error(), "clients/param_id/route.go") || strings.Contains(err.Error(), "go.mod") {
		t.Fatal(err)
	}
}

func TestGenerateRejectsUnderscoreFile(t *testing.T) {
	dir := t.TempDir()
	routes := filepath.Join(dir, "routes")
	writeFile(t, filepath.Join(routes, "_auth.go"), "package routes\n")
	_, err := Generate(context.Background(), Options{Dir: routes})
	if err == nil || !strings.Contains(err.Error(), "pathless_auth.go") || !strings.Contains(err.Error(), "ignores") || strings.Contains(err.Error(), "go.mod") {
		t.Fatal(err)
	}
}

func TestGenerateAllowsUnderscoreDirectory(t *testing.T) {
	dir := t.TempDir()
	routes := filepath.Join(dir, "routes")
	writeFile(t, filepath.Join(dir, "go.mod"), "module example.com/app\n\ngo 1.23.0\n")
	writeFile(t, filepath.Join(routes, "_auth", "login.go"), "package pathless_auth\n\nfunc Login() {}\n")
	if _, err := Generate(context.Background(), Options{Dir: routes}); err != nil {
		t.Fatal(err)
	}
}

func TestGenerateRejectsRoutePath(t *testing.T) {
	dir := t.TempDir()
	routes := filepath.Join(dir, "routes")
	writeFile(t, filepath.Join(routes, "about.tsx"), "export const Route = createFileRoute(\"/nope\")({ component: () => null });\n")
	_, err := Generate(context.Background(), Options{Dir: routes})
	if err == nil || !strings.Contains(err.Error(), "/about") {
		t.Fatal(err)
	}
}

func TestGenerateRejectsTemplatePath(t *testing.T) {
	dir := t.TempDir()
	routes := filepath.Join(dir, "routes")
	writeFile(t, filepath.Join(routes, "about.tsx"), "export const Route = createFileRoute(`/about/${\"x\"}`)({ component: () => null });\n")
	_, err := Generate(context.Background(), Options{Dir: routes})
	if err == nil || !strings.Contains(err.Error(), "static") {
		t.Fatal(err)
	}
}

func writeFixture(t *testing.T, mod, routes, repo string) {
	t.Helper()
	writeFile(t, filepath.Join(mod, "go.mod"), "module example.com/app\n\ngo 1.23.0\n\nrequire github.com/yurimoinhos/go-n-act v0.0.0\n\nreplace github.com/yurimoinhos/go-n-act => "+filepath.ToSlash(repo)+"\n")
	writeFile(t, filepath.Join(routes, "clients", "index.go"), `package clients

import (
	"context"
	"time"
)

// Role is the caller's role.
type Role string

const (
	RoleAdmin Role = "admin"
	RoleUser  Role = "user"
)

// Client is a customer.
type Client struct {
	Name string `+"`json:\"name\"`"+`
}

// ListIn is the loader input.
type ListIn struct {
	Page  int    `+"`json:\"page\"`"+`
	Role  Role   `+"`json:\"role,omitempty\"`"+`
	Actor string `+"`json:\"actor\" route:\"server\"`"+`
}

// ListOut is the loader output.
type ListOut struct {
	Items   []Client  `+"`json:\"items\"`"+`
	Updated time.Time `+"`json:\"updated\"`"+`
}

//gnact:POST /clients
// Loader lists clients.
func Loader(ctx context.Context, in ListIn) (ListOut, error) {
	return ListOut{Items: []Client{{Name: "Ada"}}}, nil
}
`)
	writeFile(t, filepath.Join(routes, "clients", "param_id.go"), `package clients

import "context"

// GetIn selects one client.
type GetIn struct {
	ID string `+"`path:\"id\" route:\"required\"`"+`
}

// GetOut is one client.
type GetOut struct {
	Client Client `+"`json:\"client\"`"+`
}

//gnact:GET /clients/{id}
// Get loads one client.
func Get(ctx context.Context, in GetIn) (GetOut, error) {
	return GetOut{Client: Client{Name: in.ID}}, nil
}
`)
	writeFile(t, filepath.Join(routes, "clients", "helpers.go"), "package clients\n\n// Format is not an endpoint.\nfunc Format(s string) string { return s }\n")
	writeFile(t, filepath.Join(routes, "clients", "index.tsx"), "export const Route = createFileRoute(\"/clients/\")({ component: () => null });\n")
	writeFile(t, filepath.Join(routes, "clients", "route.tsx"), "export const Route = createFileRoute(\"/clients\")({ component: () => null });\n")
	writeFile(t, filepath.Join(routes, "clients", "$id.tsx"), "export const Route = createFileRoute(\"/clients/$id\")({ component: () => null });\n")
	writeFile(t, filepath.Join(routes, "clients", "index.scss"), "body { color: black; }\n")
	writeFile(t, filepath.Join(routes, "clients", "roundtrip_test.go"), `package clients

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/yurimoinhos/go-n-act"
)

func TestLoaderRoundTrip(t *testing.T) {
	r := route.NewRouter()
	if err := Register(r); err != nil {
		t.Fatal(err)
	}
	srv := &route.Server{Router: r}
	rec := post(t, srv, "/clients", "{\"page\":1}")
	if rec.Code != http.StatusOK || !strings.Contains(rec.Body.String(), "Ada") {
		t.Fatalf("loader status %d body %s", rec.Code, rec.Body.String())
	}
	rec = get(t, srv, "/clients/ada")
	if rec.Code != http.StatusOK || !strings.Contains(rec.Body.String(), "ada") {
		t.Fatalf("get ok status %d body %s", rec.Code, rec.Body.String())
	}
}

func post(t *testing.T, h http.Handler, path, body string) *httptest.ResponseRecorder {
	t.Helper()
	req := httptest.NewRequest(http.MethodPost, path, strings.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	rec := httptest.NewRecorder()
	h.ServeHTTP(rec, req)
	return rec
}

func get(t *testing.T, h http.Handler, path string) *httptest.ResponseRecorder {
	t.Helper()
	req := httptest.NewRequest(http.MethodGet, path, nil)
	rec := httptest.NewRecorder()
	h.ServeHTTP(rec, req)
	return rec
}
`)
}

func writeFile(t *testing.T, path, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

func mustGen(t *testing.T, files map[string][]byte, suffix string) []byte {
	t.Helper()
	for path, body := range files {
		if strings.HasSuffix(filepath.ToSlash(path), suffix) {
			return body
		}
	}
	var names []string
	for path := range files {
		names = append(names, path)
	}
	t.Fatalf("missing %s in %v", suffix, names)
	return nil
}

func repoRoot(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("caller")
	}
	return filepath.Dir(filepath.Dir(file))
}
