package routegen

import (
	"embed"
	"io/fs"
	"path"
	"path/filepath"
	"strings"
)

//go:embed runtime/*
var runtimeFS embed.FS

const runtimeDirName = "gnact"

func emitRuntime(routesDir string, files map[string][]byte) error {
	return fs.WalkDir(runtimeFS, "runtime", func(name string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		body, err := runtimeFS.ReadFile(name)
		if err != nil {
			return err
		}
		base := path.Base(name)
		var b strings.Builder
		b.WriteString("// Code generated by routegen. DO NOT EDIT.\n")
		b.WriteString("// Embedded from gnact ")
		b.WriteString(runtimeDirName)
		b.WriteString(" runtime — version matches the gnact binary that generated this file.\n\n")
		b.Write(body)
		out := filepath.Join(routesDir, runtimeDirName, base)
		files[out] = []byte(b.String())
		return nil
	})
}

func clientImportPath(genFile, routesDir, tsImport string) string {
	if tsImport != "" && !strings.HasPrefix(tsImport, ".") {
		return tsImport + "/client"
	}
	from := filepath.Dir(genFile)
	to := filepath.Join(routesDir, runtimeDirName, "client.ts")
	rel, err := filepath.Rel(from, to)
	if err != nil {
		return "./" + runtimeDirName + "/client.ts"
	}
	rel = filepath.ToSlash(rel)
	if !strings.HasPrefix(rel, ".") {
		rel = "./" + rel
	}
	return rel
}

func indexImportPath(routesDir, tsImport string) string {
	if tsImport != "" && !strings.HasPrefix(tsImport, ".") {
		return tsImport
	}
	_ = routesDir
	return "./" + runtimeDirName + "/index.ts"
}
